modLoader="javafml"

loaderVersion="[31,)"

[[mods]]
modId="placement_preview"
version="${file.jarVersion}"
displayName="Placement Preview"

displayURL="https://github.com/3TUSK/PlacementPreview"
logoFile="logo.png"

credits='''
Big Daddy#6555 in the Twilight Forest Discord, for the mod idea.
Williewillus for his multiblock visualization code in Patchouli.
Yuri's Cat for his awesome logo.
'''

authors="3TUSK"

description="Get to know how your block will (probably) be placed beforehand!"
